export { default as Home } from "./home";
export { default as Login } from "./login";
export { default as SignUp } from "./signUp";
export { default as SocialsLogin } from "./socialsLogin";
export { default as Services } from "./services";
export { default as Booking } from "./booking";
export { default as Reviews } from "./reviews";
export { default as Profile } from "./profile";
export { default as Calender } from "./calendar";
