export const apiConstant = {
  authentication: {
    login: "v1/auth/signin",
    signUp: "v1/auth/signup",
    otpSignUp: "v1/auth/confirm",
    forgetPasswordUsingEmail: "v1/auth/forgot-password",
    forgetPasswordUsingOTP: "v1/auth/confirm-forgot-password",
  },
  vendor: {
    getVendorDetails: "/v1/vendor/vendor_details",
    getVendorDocuments: "/v1/vendor/documents",
    getVendorOwners: "/v1/vendor/ownership_details",
    getVendorEmployees: "/v1/vendor/employees",
    sendEmployeeInvitation: "/v1/vendor/invite_employees",
    createCompanyInformation: "v1/vendor/company_details",
    createContactInformation: "v1/vendor/contact_details",
    createBusinessInformation: "v1/vendor/address",
    createBankAccountInformation: "v1/vendor/bank_details",
    createOwnershipInformation: "/v1/vendor/ownership_details",
    createVendorDocument: "/v1/vendor/create_document",
    updateVendorDocument: "/v1/vendor/update_document",
    updateEmployeePermission: "/v1/vendor/update_employee_permissions",
    deleteVendorDocument: "/v1/vendor/document",
    deleteVendorEmployee: "/v1/vendor/employee",
    getAllServices: "/v1/vendor/products",
    getAllPriceBook: "/v1/vendor/pricebook",
    updatePriceBook: "/v1/vendor/pricebook/update",
    getServicesByPriceBookId: "/v1/vendor/pricebooks",
    getServiceById: "/v1/product/info?productId",
    updateServiceById: "/v1/product/update",
    deleteImageById: "/v1/product/image",
    getVendorInvites: "/v1/vendor/invites",
    createVendorEmployeeRequest: "/v1/vendor/employee_request",
    getAllVendorsForInvitation: "/v1/vendor/request_vendors",
  },
  review: {
    getAllReview: "/v1/vendor/review",
    getReviewById: "/v1/vendor/review",
    getCalendar: "/v1/vendor/calendar/get_events",
  },
  uploadImage: {
    getS3Url: "/v1/upload/get_S3_url",
  },
  user: {
    getUserDetails: "/v1/user/personal_details",
    updateUserDetails: "/v1/user/update_details",
  },
};
