

//api const
export const apiConstant = {
  authentication: {
    login: "v1/auth/signin",
    signUp: "v1/auth/signup",
    otpSignUp: "v1/auth/confirm",
    resendOtp: "v1/auth/resend_otp",
    forgetPasswordUsingEmail: "v1/auth/forgot-password",
    forgetPasswordUsingOTP: "v1/auth/confirm_forgot_password",
  },
  vendor: {
    getVendorDetails: "/v1/vendor/vendor_details",
    getVendorDocuments: "/v1/vendor/documents",
    getVendorOwners: "/v1/vendor/ownership_details",
    getVendorEmployees: "/v1/vendor/employees",
    getVendorNotifications: "/v1/vendor/notifications",
    sendEmployeeInvitation: "/v1/vendor/employees/invite",
    createCompanyInformation: "v1/vendor/company_details",
    createContactInformation: "v1/vendor/contact_details",
    createBusinessInformation: "v1/vendor/address",
    createBankAccountInformation: "v1/vendor/bank_details",
    createOwnershipInformation: "/v1/vendor/ownership_details",
    createVendorDocument: "/v1/vendor/create_document",
    updateVendorDocument: "/v1/vendor/update_document",
    updateEmployeePermission: "/v1/vendor/employees/permissions",
    getEmployeePermissions: "/v1/vendor/employees/permissions",
    deleteVendorDocument: "/v1/vendor/document",
    deleteVendorEmployee: "/v1/vendor/employees",
    uploadCompanyLogo: "/v1/vendor/company_logo",
    getAllServices: "/v1/vendor/product/meta",
    getAllPriceBook: "/v1/vendor/pricebook",
    createPriceBook: "/v1/vendor/pricebook/create",
    deletePriceBook: "/v1/vendor/pricebook",
    updatePriceBook: "/v1/vendor/pricebook/update",
    getServicesByPriceBookId: "/v1/vendor/pricebook/products",
    getServiceById: "/v1/product/info?productId",
    deleteServiceById: "/v1/product/delete",
    updateServiceById: "/v1/product/update",
    createService: "/v1/product/create",
    deleteImageById: "/v1/product/image",
    deleteBannerImage: "/v1/product/banner",
    deleteCompanyLogo: "/v1/vendor/company_logo",
    getVendorInvites: "/v1/vendor/invites",
    createVendorEmployeeRequest: "/v1/vendor/employee_request",
    acceptVendorInvite: "/v1/vendor/accept_invite",
    getAllVendorsForInvitation: "/v1/vendor/request_vendors",
    getAllSearchItems: "/v1/vendor/searchitems",
  },
  review: {
    getAllReview: "/v1/vendor/review",
    getReviewById: "/v1/vendor/review",
    getCalendar: "/v1/vendor/calendar/get_events",
  },
  uploadImage: {
    getS3Url: "/v1/upload/get_S3_url",
  },
  user: {
    getUserDetails: "/v1/user/personal_details",
    updateUserDetails: "/v1/user/update_details",
    updateProfileImage: "/v1/user/profile_picture",
    deleteProfileImage: "/v1/user/profile_picture",
  },
  booking: {
    createExternalBooking: "v1/booking/create_external_booking",
    getAllBookings: "v1/booking/",
    getBookingItemDetailsById: "v1/booking",
  },
};
